// Catálogo Completo de Supermercados, Encartes e Produtos (com Ofertas de Referência Única e Múltiplas)
// Colina de Laranjeiras & Imediações (Serra / ES)

const SUPERMARKETS = [
  {
    id: 'extrabom',
    name: 'Extrabom Supermercados',
    location: 'Colina de Laranjeiras (Shopping Montserrat)',
    badge: 'No Bairro',
    color: '#e63946',
    distance: '0.4 km',
    isLocal: true
  },
  {
    id: 'carone',
    name: 'Carone Supermercados',
    location: 'Laranjeiras (Av. Central)',
    badge: 'Imediações',
    color: '#0077b6',
    distance: '1.2 km',
    isLocal: false
  },
  {
    id: 'perim',
    name: 'Perim Supermercados',
    location: 'Laranjeiras (Av. Eldes Scherrer)',
    badge: 'Imediações',
    color: '#2a9d8f',
    distance: '1.5 km',
    isLocal: false
  },
  {
    id: 'atacadao',
    name: 'Atacadão Serra',
    location: 'Colina de Laranjeiras (BR-101 Norte)',
    badge: 'Atacarejo No Bairro',
    color: '#f4a261',
    distance: '0.8 km',
    isLocal: true
  },
  {
    id: 'assai',
    name: 'Assaí Atacadista',
    location: 'Laranjeiras / Civit',
    badge: 'Atacarejo',
    color: '#023e8a',
    distance: '1.8 km',
    isLocal: false
  },
  {
    id: 'ok_super',
    name: 'OK Superatacado',
    location: 'Laranjeiras (Av. Eldes Scherrer)',
    badge: 'Atacarejo',
    color: '#e76f51',
    distance: '1.6 km',
    isLocal: false
  },
  {
    id: 'epa',
    name: 'EPA Supermercados',
    location: 'Laranjeiras',
    badge: 'Imediações',
    color: '#d62828',
    distance: '1.4 km',
    isLocal: false
  }
];

const ENCARTES = [
  { id: 1, file: 'campanha-169512-cluster-541-pagina-1.jpeg', title: 'Assaí: Acelera com Preço Baixo (Capa)', market: 'assai', validity: 'Válido 07/08 a 08/08' },
  { id: 2, file: 'campanha-169512-cluster-541-pagina-2.jpeg', title: 'Assaí: Laticínios, Limpeza e Cervejas', market: 'assai', validity: 'Válido 07/08 a 08/08' },
  { id: 3, file: 'WhatsApp Image 2026-08-07 at 08.18.24.jpeg', title: 'Atacadão BR-101: Especial Aves Copacol', market: 'atacadao', validity: 'Ofertas da Semana' },
  { id: 4, file: 'WhatsApp Image 2026-08-07 at 09.00.44.jpeg', title: 'Atacadão BR-101: Super Sexta Café Número Um', market: 'atacadao', validity: 'Válido 07/08' },
  { id: 5, file: 'WhatsApp Image 2026-08-07 at 09.15.47.jpeg', title: 'Carone: Especial Ofertas Dia dos Pais', market: 'carone', validity: 'Válido 07/08 a 08/08' },
  { id: 6, file: 'WhatsApp Image 2026-08-07 at 13.00.42.jpeg', title: 'Carone: Especial Destilados Dia dos Pais', market: 'carone', validity: 'Válido 03/08 a 09/08' },
  { id: 7, file: 'oferta-pagina-9.png', title: 'Extrabom: Especial Limpeza Downy e Ariel', market: 'extrabom', validity: 'Válido até 12/08' }
];

const CATEGORIES = [
  { id: 'all', name: 'Todas as Ofertas', icon: '🏷️' },
  { id: 'acougue', name: 'Açougue & Carnes', icon: '🥩' },
  { id: 'hortifruti', name: 'Hortifrúti & Frutas', icon: '🥦' },
  { id: 'laticinios', name: 'Laticínios & Frios', icon: '🧀' },
  { id: 'mercearia', name: 'Mercearia & Matinais', icon: '🌾' },
  { id: 'bebidas', name: 'Bebidas & Cervejas', icon: '🥤' },
  { id: 'limpeza', name: 'Limpeza & Casa', icon: '🧹' },
  { id: 'higiene', name: 'Higiene & Perfumaria', icon: '🧴' }
];

const PRODUCTS = [
  // ==========================================
  // --- ASSAÍ ATACADISTA (OFERTAS DO ENCARTE OFICIAL) ---
  // ==========================================
  {
    id: 'assai_1',
    name: 'Lasanha Congelada Sadia Sabores 600g',
    category: 'laticinios',
    unit: '600g',
    image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=400&auto=format&fit=crop&q=80',
    encarteId: 2,
    offerMarketId: 'assai',
    offerPrice: 13.90,
    validity: 'Válido 07/08 a 08/08',
    prices: { assai: 13.90 },
    featured: true,
    discountTag: '📌 Exclusivo Assaí'
  },
  {
    id: 'assai_2',
    name: 'Salsicha para Hot-Dog Congelada Seara 5kg',
    category: 'acougue',
    unit: '5kg',
    image: 'https://images.unsplash.com/photo-1627042637241-15b026607212?w=400&auto=format&fit=crop&q=80',
    encarteId: 2,
    offerMarketId: 'assai',
    offerPrice: 37.45,
    validity: 'Válido 07/08 a 08/08',
    prices: { assai: 37.45 },
    featured: false,
    discountTag: '📌 Exclusivo Assaí'
  },
  {
    id: 'assai_3',
    name: 'Margarina com ou sem Sal Qualy Pote 500g',
    category: 'laticinios',
    unit: '500g',
    image: 'https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?w=400&auto=format&fit=crop&q=80',
    encarteId: 2,
    offerMarketId: 'assai',
    offerPrice: 8.99,
    validity: 'Válido 07/08 a 08/08',
    prices: { assai: 8.99, extrabom: 10.90, carone: 11.50 },
    featured: true,
    discountTag: 'Qualy 500g R$ 8,99'
  },
  {
    id: 'assai_4',
    name: 'Hambúrguer Misto Congelado Texas Burger Seara 672g',
    category: 'acougue',
    unit: '672g',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&auto=format&fit=crop&q=80',
    encarteId: 2,
    offerMarketId: 'assai',
    offerPrice: 11.90,
    validity: 'Válido 07/08 a 08/08',
    prices: { assai: 11.90 },
    featured: false,
    discountTag: '📌 Exclusivo Assaí'
  },
  {
    id: 'assai_5',
    name: 'Iogurte Líquido Porto Alegre Sabores PET 1.25kg',
    category: 'laticinios',
    unit: '1.25kg',
    image: 'https://images.unsplash.com/photo-1563636619-e9143da7973b?w=400&auto=format&fit=crop&q=80',
    encarteId: 2,
    offerMarketId: 'assai',
    offerPrice: 9.90,
    validity: 'Válido 07/08 a 08/08',
    prices: { assai: 9.90 },
    featured: false,
    discountTag: '📌 Exclusivo Assaí'
  },
  {
    id: 'assai_6',
    name: 'Farinha de Mandioca Branca/Amarela Tipo 1 Ana 1kg',
    category: 'mercearia',
    unit: '1kg',
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&auto=format&fit=crop&q=80',
    encarteId: 2,
    offerMarketId: 'assai',
    offerPrice: 3.69,
    validity: 'Válido 07/08 a 08/08',
    prices: { assai: 3.69 },
    featured: false,
    discountTag: '📌 Exclusivo Assaí'
  },
  {
    id: 'assai_7',
    name: 'Macarrão Instantâneo Lámen Nissin Sabores 85g',
    category: 'mercearia',
    unit: '85g',
    image: 'https://images.unsplash.com/photo-1612927601601-6638404737ce?w=400&auto=format&fit=crop&q=80',
    encarteId: 2,
    offerMarketId: 'assai',
    offerPrice: 1.99,
    validity: 'Válido 07/08 a 08/08',
    prices: { assai: 1.99, extrabom: 2.39, atacadao: 2.19 },
    featured: true,
    discountTag: 'App Assaí R$ 1,99'
  },
  {
    id: 'assai_8',
    name: 'Bebida Láctea Nescau Nestlé TP 180ml',
    category: 'laticinios',
    unit: '180ml',
    image: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=400&auto=format&fit=crop&q=80',
    encarteId: 2,
    offerMarketId: 'assai',
    offerPrice: 1.69,
    validity: 'Válido 07/08 a 08/08',
    prices: { assai: 1.69 },
    featured: false,
    discountTag: '📌 Exclusivo Assaí'
  },
  {
    id: 'assai_9',
    name: 'Milho-Verde Predilecta Lata 170g',
    category: 'mercearia',
    unit: '170g',
    image: 'https://images.unsplash.com/photo-1551754655-cd27e38d2076?w=400&auto=format&fit=crop&q=80',
    encarteId: 2,
    offerMarketId: 'assai',
    offerPrice: 2.49,
    validity: 'Válido 07/08 a 08/08',
    prices: { assai: 2.49, atacadao: 2.79, carone: 2.99 },
    featured: false,
    discountTag: 'Predilecta R$ 2,49'
  },
  {
    id: 'assai_10',
    name: 'Maionese Hellmann\'s Pack 2x500g',
    category: 'mercearia',
    unit: 'pack 2x500g',
    image: 'https://images.unsplash.com/photo-1528751014936-863e6e7a319c?w=400&auto=format&fit=crop&q=80',
    encarteId: 2,
    offerMarketId: 'assai',
    offerPrice: 16.90,
    validity: 'Válido 07/08 a 08/08',
    prices: { assai: 16.90 },
    featured: true,
    discountTag: '📌 Exclusivo Assaí'
  },
  {
    id: 'assai_11',
    name: 'Cerveja Amstel Lager Latão 473ml',
    category: 'bebidas',
    unit: '473ml',
    image: 'assets/cerveja.png',
    encarteId: 2,
    offerMarketId: 'assai',
    offerPrice: 3.89,
    validity: 'Válido 07/08 a 08/08',
    prices: { assai: 3.89, atacadao: 3.99, extrabom: 4.49, carone: 4.39 },
    featured: true,
    discountTag: 'App Assaí R$ 3,89'
  },
  {
    id: 'assai_12',
    name: 'Cerveja Antarctica Original Latão 473ml',
    category: 'bebidas',
    unit: '473ml',
    image: 'assets/cerveja.png',
    encarteId: 2,
    offerMarketId: 'assai',
    offerPrice: 4.49,
    validity: 'Válido 07/08 a 08/08',
    prices: { assai: 4.49, atacadao: 4.69, carone: 4.99 },
    featured: true,
    discountTag: 'App Assaí R$ 4,49'
  },
  {
    id: 'assai_13',
    name: 'Cerveja Amstel Ultra Lager Lata 269ml',
    category: 'bebidas',
    unit: '269ml',
    image: 'assets/cerveja.png',
    encarteId: 2,
    offerMarketId: 'assai',
    offerPrice: 3.49,
    validity: 'Válido 07/08 a 08/08',
    prices: { assai: 3.49 },
    featured: false,
    discountTag: '📌 Exclusivo Assaí'
  },
  {
    id: 'assai_14',
    name: 'Cerveja Spaten Latão 473ml',
    category: 'bebidas',
    unit: '473ml',
    image: 'assets/cerveja.png',
    encarteId: 2,
    offerMarketId: 'assai',
    offerPrice: 4.49,
    validity: 'Válido 07/08 a 08/08',
    prices: { assai: 4.49, atacadao: 4.59, carone: 4.89, perim: 4.99 },
    featured: true,
    discountTag: 'App Assaí R$ 4,49'
  },
  {
    id: 'assai_15',
    name: 'Vinho Tinto Suave Pérgola PET 1.45L',
    category: 'bebidas',
    unit: '1.45L',
    image: 'assets/cerveja.png',
    encarteId: 2,
    offerMarketId: 'assai',
    offerPrice: 22.90,
    validity: 'Válido 07/08 a 08/08',
    prices: { assai: 22.90 },
    featured: false,
    discountTag: '📌 Exclusivo Assaí'
  },
  {
    id: 'assai_16',
    name: 'Gin Dry Cat Tipos Garrafa 750ml',
    category: 'bebidas',
    unit: '750ml',
    image: 'assets/cerveja.png',
    encarteId: 2,
    offerMarketId: 'assai',
    offerPrice: 58.90,
    validity: 'Válido 07/08 a 08/08',
    prices: { assai: 58.90 },
    featured: false,
    discountTag: '📌 Exclusivo Assaí'
  },
  {
    id: 'assai_17',
    name: 'Refrigerante Guaraná Coroa PET 600ml',
    category: 'bebidas',
    unit: '600ml',
    image: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=400&auto=format&fit=crop&q=80',
    encarteId: 2,
    offerMarketId: 'assai',
    offerPrice: 1.99,
    validity: 'Válido 07/08 a 08/08',
    prices: { assai: 1.99 },
    featured: false,
    discountTag: '📌 Exclusivo Assaí'
  },
  {
    id: 'assai_18',
    name: 'Refresco Dafruta Sabores TP 1L',
    category: 'bebidas',
    unit: '1L',
    image: 'https://images.unsplash.com/photo-1613478223719-2ab802602423?w=400&auto=format&fit=crop&q=80',
    encarteId: 2,
    offerMarketId: 'assai',
    offerPrice: 3.19,
    validity: 'Válido 07/08 a 08/08',
    prices: { assai: 3.19 },
    featured: false,
    discountTag: '📌 Exclusivo Assaí'
  },
  {
    id: 'assai_19',
    name: 'Bebida Energética Daly Sabores PET 2L',
    category: 'bebidas',
    unit: '2L',
    image: 'https://images.unsplash.com/photo-1622543925917-763c34d1a86e?w=400&auto=format&fit=crop&q=80',
    encarteId: 2,
    offerMarketId: 'assai',
    offerPrice: 9.79,
    validity: 'Válido 07/08 a 08/08',
    prices: { assai: 9.79 },
    featured: false,
    discountTag: '📌 Exclusivo Assaí'
  },
  {
    id: 'assai_20',
    name: 'Água Mineral Sem Gás Klas PET 500ml',
    category: 'bebidas',
    unit: '500ml',
    image: 'https://images.unsplash.com/photo-1548839140-29a749e1bc4e?w=400&auto=format&fit=crop&q=80',
    encarteId: 2,
    offerMarketId: 'assai',
    offerPrice: 0.79,
    validity: 'Válido 07/08 a 08/08',
    prices: { assai: 0.79, atacadao: 0.89 },
    featured: false,
    discountTag: 'PET 500ml R$ 0,79'
  },
  {
    id: 'assai_21',
    name: 'Detergente Líquido Barra Fragrâncias Frasco 500ml',
    category: 'limpeza',
    unit: '500ml',
    image: 'https://images.unsplash.com/photo-1585837575652-267c041d77d4?w=400&auto=format&fit=crop&q=80',
    encarteId: 2,
    offerMarketId: 'assai',
    offerPrice: 1.29,
    validity: 'Válido 07/08 a 08/08',
    prices: { assai: 1.29, extrabom: 1.59, atacadao: 1.49 },
    featured: true,
    discountTag: 'App Assaí R$ 1,29'
  },
  {
    id: 'assai_22',
    name: 'Lava-Roupas Líquido Tudo em Um Ápyce Galão 5L',
    category: 'limpeza',
    unit: '5L',
    image: 'https://images.unsplash.com/photo-1610557892470-55d9e80c0bce?w=400&auto=format&fit=crop&q=80',
    encarteId: 2,
    offerMarketId: 'assai',
    offerPrice: 14.95,
    validity: 'Válido 07/08 a 08/08',
    prices: { assai: 14.95 },
    featured: true,
    discountTag: '📌 Exclusivo Assaí'
  },
  {
    id: 'assai_23',
    name: 'Lava-Roupas em Pó Surf Tipos Bag 2.4kg',
    category: 'limpeza',
    unit: '2.4kg',
    image: 'https://images.unsplash.com/photo-1610557892470-55d9e80c0bce?w=400&auto=format&fit=crop&q=80',
    encarteId: 2,
    offerMarketId: 'assai',
    offerPrice: 18.95,
    validity: 'Válido 07/08 a 08/08',
    prices: { assai: 18.95, extrabom: 22.90, carone: 21.90 },
    featured: true,
    discountTag: 'Bag 2,4kg R$ 18,95'
  },
  {
    id: 'assai_24',
    name: 'Fralda Descartável Hiper Huggies Pacote',
    category: 'higiene',
    unit: 'pacote',
    image: 'https://images.unsplash.com/photo-1519689680058-324335c77eba?w=400&auto=format&fit=crop&q=80',
    encarteId: 2,
    offerMarketId: 'assai',
    offerPrice: 49.90,
    validity: 'Válido 07/08 a 08/08',
    prices: { assai: 49.90, carone: 54.90 },
    featured: true,
    discountTag: 'App Assaí R$ 49,90'
  },
  {
    id: 'assai_25',
    name: 'Papel Higiênico Folha Dupla Olé 12 Rolo (L12 P11)',
    category: 'higiene',
    unit: '12 rolos',
    image: 'https://images.unsplash.com/photo-1584556812952-905ffd0c611a?w=400&auto=format&fit=crop&q=80',
    encarteId: 2,
    offerMarketId: 'assai',
    offerPrice: 6.99,
    validity: 'Válido 07/08 a 08/08',
    prices: { assai: 6.99 },
    featured: false,
    discountTag: '📌 Exclusivo Assaí'
  },

  // ==========================================
  // --- OUTRAS OFERTAS DE OUTROS ENCARTES ---
  // ==========================================
  {
    id: 'p1',
    name: 'Contrafilé Bovino Resfriado Friboi (Peça/Pedaço kg)',
    category: 'acougue',
    unit: 'kg',
    image: 'assets/contrafile.png',
    encarteId: 1,
    offerMarketId: 'assai',
    offerPrice: 49.90,
    validity: 'Válido 07/08 a 08/08',
    prices: { assai: 49.90, atacadao: 52.90, extrabom: 59.90, carone: 58.90, perim: 62.50, ok_super: 53.90, epa: 67.90 },
    featured: true,
    discountTag: 'App Assaí R$ 49,90/kg'
  },
  {
    id: 'p2',
    name: 'Arroz Branco Tipo 1 Puro Grão 5kg',
    category: 'mercearia',
    unit: '5kg',
    image: 'assets/arroz.png',
    encarteId: 1,
    offerMarketId: 'assai',
    offerPrice: 15.79,
    validity: 'Válido 07/08 a 08/08',
    prices: { assai: 15.79, atacadao: 18.90, extrabom: 22.90, carone: 23.50, perim: 24.90, ok_super: 19.20, epa: 25.90 },
    featured: true,
    discountTag: 'Mega Preço R$ 15,79'
  },
  {
    id: 'p3',
    name: 'Café Tradicional ou Extraforte Número Um 250g',
    category: 'mercearia',
    unit: '250g',
    image: 'assets/cafe.png',
    encarteId: 4,
    offerMarketId: 'atacadao',
    offerPrice: 8.99,
    validity: 'Super Sexta 07/08',
    prices: { atacadao: 8.99, assai: 8.69, extrabom: 12.89, carone: 11.90, perim: 12.50, ok_super: 9.50, epa: 13.80 },
    featured: true,
    discountTag: 'Super Sexta Atacadão'
  },
  {
    id: 'p19',
    name: 'Petisco de Frango Temperado Copacol Congelado 1kg',
    category: 'acougue',
    unit: '1kg',
    image: 'https://images.unsplash.com/photo-1604503468506-a8da13d82791?w=400&auto=format&fit=crop&q=80',
    encarteId: 3,
    offerMarketId: 'atacadao',
    offerPrice: 16.90,
    validity: 'Oferta da Semana',
    prices: { atacadao: 16.90 },
    featured: true,
    discountTag: '📌 Exclusivo Atacadão'
  },
  {
    id: 'p4',
    name: 'Café Torrado e Moído Melitta 500g',
    category: 'mercearia',
    unit: '500g',
    image: 'assets/cafe.png',
    encarteId: 5,
    offerMarketId: 'carone',
    offerPrice: 24.98,
    validity: 'Válido 07/08 a 08/08',
    prices: { carone: 24.98, extrabom: 28.90, perim: 29.90, atacadao: 25.90, assai: 25.50, ok_super: 26.90, epa: 29.99 },
    featured: false,
    discountTag: 'Clube Carone R$ 24,98'
  },
  {
    id: 'p5',
    name: 'Caixa de Bombons Sortidos Garoto 220g',
    category: 'mercearia',
    unit: '220g',
    image: 'https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=400&auto=format&fit=crop&q=80',
    encarteId: 5,
    offerMarketId: 'carone',
    offerPrice: 11.99,
    validity: 'Válido 07/08 a 08/08',
    prices: { carone: 11.99, extrabom: 13.98, perim: 14.50, atacadao: 12.50, assai: 12.30, ok_super: 12.90, epa: 14.90 },
    featured: true,
    discountTag: 'Especial Dia dos Pais'
  },
  {
    id: 'p15',
    name: 'Amaciante Concentrado Downy 1L (Perfuma e Premia)',
    category: 'limpeza',
    unit: '1L',
    image: 'https://images.unsplash.com/photo-1585837575652-267c041d77d4?w=400&auto=format&fit=crop&q=80',
    encarteId: 7,
    offerMarketId: 'extrabom',
    offerPrice: 18.99,
    validity: 'Válido até 12/08',
    prices: { extrabom: 18.99 },
    featured: true,
    discountTag: '📌 Exclusivo Extrabom'
  },
  {
    id: 'p16',
    name: 'Sabão Líquido Ariel Cores Radiantes 3L',
    category: 'limpeza',
    unit: '3L',
    image: 'https://images.unsplash.com/photo-1610557892470-55d9e80c0bce?w=400&auto=format&fit=crop&q=80',
    encarteId: 7,
    offerMarketId: 'extrabom',
    offerPrice: 34.90,
    validity: 'Válido até 12/08',
    prices: { extrabom: 34.90 },
    featured: true,
    discountTag: '📌 Exclusivo Extrabom'
  },
  {
    id: 'p17',
    name: 'Whisky Escocês Chivas Regal 12Y 750ml',
    category: 'bebidas',
    unit: '750ml',
    image: 'assets/cerveja.png',
    encarteId: 6,
    offerMarketId: 'carone',
    offerPrice: 99.90,
    validity: 'Válido 03/08 a 09/08',
    prices: { carone: 99.90 },
    featured: true,
    discountTag: '📌 Exclusivo Carone'
  },
  {
    id: 'p18',
    name: 'Gin Inglês Beefeater Sabores 750ml',
    category: 'bebidas',
    unit: '750ml',
    image: 'assets/cerveja.png',
    encarteId: 6,
    offerMarketId: 'carone',
    offerPrice: 89.90,
    validity: 'Válido 03/08 a 09/08',
    prices: { carone: 89.90 },
    featured: false,
    discountTag: '📌 Exclusivo Carone'
  },
  {
    id: 'p21',
    name: 'Banana Prata Selecionada (kg)',
    category: 'hortifruti',
    unit: 'kg',
    image: 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=400&auto=format&fit=crop&q=80',
    encarteId: 5,
    offerMarketId: 'perim',
    offerPrice: 3.99,
    validity: 'Feira Perim 07/08',
    prices: { perim: 3.99 },
    featured: true,
    discountTag: '📌 Exclusivo Perim'
  },
  {
    id: 'p22',
    name: 'Tomate Longa Vida de Primeira (kg)',
    category: 'hortifruti',
    unit: 'kg',
    image: 'assets/tomate.png',
    encarteId: 7,
    offerMarketId: 'extrabom',
    offerPrice: 4.98,
    validity: 'Feira Extrabom',
    prices: { extrabom: 4.98 },
    featured: false,
    discountTag: '📌 Exclusivo Extrabom'
  },
  {
    id: 'p24',
    name: 'Leite UHT Integral Italac 1L',
    category: 'laticinios',
    unit: '1L',
    image: 'https://images.unsplash.com/photo-1563636619-e9143da7973b?w=400&auto=format&fit=crop&q=80',
    encarteId: 4,
    offerMarketId: 'atacadao',
    offerPrice: 4.19,
    validity: 'Super Sexta Atacadão',
    prices: { atacadao: 4.19 },
    featured: false,
    discountTag: '📌 Exclusivo Atacadão'
  }
];

const COMMUNITY_TIPS = [
  {
    author: 'Mariana S. (Moradora de Colina)',
    market: 'Assaí Atacadista',
    text: 'Contrafilé Friboi tá por R$ 49,90 no App Meu Assaí hoje!',
    time: 'Há 15 minutos'
  },
  {
    author: 'Carlos Eduardo',
    market: 'Atacadão BR-101',
    text: 'Café Número Um tá R$ 8,99 na Super Sexta do Atacadão!',
    time: 'Há 45 minutos'
  },
  {
    author: 'Fernanda Lima',
    market: 'Carone Laranjeiras',
    text: 'Gin Beefeater tá por R$ 89,90 no Clube Carone!',
    time: 'Há 2 horas'
  }
];
